version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    depends_on:
      - db
    volumes:
      - ./:/var/www/html/
    ports:
      - 8443:443
  db:
    container_name: db
    image: mysql
    command: ['--sql_mode=']
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: chippenham
        MYSQL_DATABASE: chippenham
        MYSQL_USER: chippenham
        MYSQL_PASSWORD: chippenham
    ports:
        - "9906:3306"
    volumes:
      - database:/var/lib/mysql

volumes:
  database:
